### ISSUE TITLE
Homepage: broken ui

### ISSUE THREAD

**Issue by leejh3224** [chiefGui/reshader#1]
link to github is blocked by the message " Scroll down to see more"

**Comment by chiefGui** [comment]
Hey @leejh3224! Sorry for the late response.

Could you provide me some details of the device you used when you faced this issue?

**Comment by leejh3224** [comment]
Hi @chiefGui,

For your information, I'm using latest version of chrome@65.0.3325.181 and laptop(Mac OS).

<img width="779" alt="2018-04-14 4 48 35" src="https://user-images.githubusercontent.com/25929117/38765839-09666de0-4004-11e8-98a4-ca748f0e90ba.png">

I have no idea whether it's intended or not but the message "scroll down to see more" is hard to recognize as it is white and small without any background div.

Also, I was not able to click on github button or quick start button because of "scroll down to see more" message. It's blocking those two buttons.

<img width="427" alt="2018-04-14 4 53 43" src="https://user-images.githubusercontent.com/25929117/38765861-6f4d8f44-4004-11e8-8c2d-cc1fb5b97367.png">

It would be nice to move "scroll down to see more" message down a bit so that I can see the message and also able to click the github and quick start link.

**Comment by chiefGui** [comment]
Though a little bit late, I've fixed this issue in the latest website update.

Let me know if the error persists. Thanks!
